### ISSUE TITLE
Calling Incident.to_dict() removes console connection

### ISSUE THREAD

**Issue by creideiki** [thinkst/canarytools-python#15]
I wanted to get unacknowledged incidents, export them in JSON format, and acknowledge them.

I did this:
```python
console = canarytools.Console(api_key=token, domain=domain)
incidents = console.incidents.unacknowledged()
i = incidents[0]
d = i.to_dict()
# Pull out some fields of "d" into plain text, then "json.dumps(d)".
i.acknowledge()
```
However, the `i.acknowledge()` call fails with:
```
  File "/home/user/.local/lib/python3.11/site-packages/canarytools/models/incidents.py", line 300, in acknowledge
    r = self.console.post('incident/acknowledge', params)
        ^^^^^^^^^^^^
AttributeError: 'IncidentHTTPLogin' object has no attribute 'console'
```
This seems to be because the `to_dict()` method inadvertently destroys the `console` field of the `Incident` object when all it wants is not to return it: https://github.com/thinkst/canarytools-python/blob/379638f91f2a15837af7ea948aeddb8f391bc634/canarytools/models/incidents.py#L340-L348

What you probably want instead is to make a copy of `self.__dict__` before editing it:
```python
from copy import deepcopy

incident_dict = deepcopy(self.__dict__)
```

I've run a quick test of this, and it seems to work.

**Comment by azh-r** [comment]
Thanks for finding and fixing this @creideiki ! If your check your Github email, we've sent along a link to a gift to say thanks.
