### ISSUE TITLE
[BUG] Missing support for Cloned CSS tokens

### ISSUE THREAD

**Issue by jesseops** [thinkst/canarytools-python#19]
**Describe the bug**
The Python SDK does not have definitions for some CanaryTokens, I'm specifically affected by the missing `cloned-css` definition. `expected_referrer` is the required parameter (based on the behavior of the Canary Tools web console), but that parameter is not allowed by the `CanaryTokens.create` method in `canarytools/models/canarytokens.py`.

I have [created a PR](https://github.com/thinkst/canarytools-python/pull/18) to address this issue

**To Reproduce**
1. Call the `create` method with valid arguments, eg `create("Test Token", "cloned-css", flock_id="<some-flock-id>", expected_referrer="example.com")`
2. Exception is thrown: `TypeError: CanaryTokens.create() got an unexpected keyword argument 'expected_referrer'`

**Expected behavior**
I expect to receive a confirmation that the token was created.

**Screenshots**
N/A

 **Desktop (please complete the following information):**
 N/A

 **Smartphone (please complete the following information):**
 N/A

**Additional context**
N/A

**Comment by thinkst-pieter** [comment]
Hi @jesseops, thanks for the PR. I have accepted and merged it.
Keep an eye out for the response on your support desk ticket with a link to a gift to say thank you.

**Comment by jesseops** [comment]
Thanks @thinkst-pieter!
