### ISSUE TITLE
Last item in console.tokens.all() does not have a canarytoken attribute

### ISSUE THREAD

**Issue by JPvRiel** [thinkst/canarytools-python#5]
**Expectation:**

As a user of this python canarytools API wrapper, I'd expect that the list of tokens returned have at least a key or canarytoken (shorter unqualified key) attribute irrespective of token type.

**Observation:**

The last item returned does not seem to be a full/proper canary token object.

Example use:

```python
tokens = console.tokens.all()
for t in tokens:
   print(t.canarytoken)
```

Observed exception when running the above:

```console
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
AttributeError: 'CanaryToken' object has no attribute 'canarytoken'
```

Inspecting the last object of the list returned vs the prior 2nd last object, it's clear many attributes in the last token object returned are not set.

```console
>>> dir(tokens[-1])
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'console', 'delete', 'disable', 'enable', 'endpoints', 'parse', 'update']
>>> dir(tokens[-2])
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'canarytoken', 'console', 'created', 'created_printable', 'delete', 'disable', 'enable', 'enabled', 'exe_name', 'exe_type', 'flock_id', 'hostname', 'key', 'kind', 'memo', 'node_id', 'parse', 'triggered_count', 'update', 'url']
```

Workaround:

```python
tokens = [t for t in console.tokens.all() if hasattr(t, 'canarytoken')]
```

**Comment by thinkst** [comment]
Hey @JPvRiel,

Would you mind emailing me at jay [at] thinkst [dot] com with some of your Canary console details? This way I can try reproduce the issue.

**Comment by thinkst** [comment]
Hey @JPvRiel,

Ive pushed an update to this repo and to the pypi package. Would you mind updating and letting me know if this issue has been resolved for you?

**Comment by JPvRiel** [comment]
I get a new exception now: `canarytools.exceptions.ConsoleError: Invalid or duplicated parameter: include_endpoints` with the same demo test code I used in v1.0.7. Emailed you details. Perhaps it's something specific to our console.

**Comment by JPvRiel** [comment]
Post the recent update to our console, v1.0.8 works now - thanks for the fix!
